use preguntation_db;

INSERT INTO questions (question, correct_answer) VALUES
('En que año salio Rocky IV?', 3),
('Quien escribio "El Cantante"?', 6),
('Anotador del primer gol de Peru en un mundial', 9),
('Ganador mundial de Sud Africa 2010', 10),
('Como se dice coche de bebe en Ingles?', 14),
('Como se dice Hola en Aleman?', 18),
('Cuántas películas tiene la saga de harry potter', 21),
('En que año nacio Pedro Suarez Bertiz', 23),
('Como se dice llave en Ingles?', 26),
('Quien anoto el primer gol de Peru en el mundial 2018?', 28);

INSERT INTO answers (id_question, answer) VALUES
(1, '1990'),
(1, '1988'),
(1, '1985'),
(2, 'Willie Colon'),
(2, 'Hector Lavoe'),
(2, 'Ruben Blades'),
(3, 'Julio Cesar Uribe'),
(3, 'Teofilo Cubillas'),
(3, 'Luis de Souza'),
(4, 'España'),
(4, 'Brasil'),
(4, 'Alemania'),
(5, 'Car'),
(5, 'Stroller'),
(5, 'Baby Seat'),
(6, 'Hello'),
(6, 'Ciao'),
(6, 'Hallo'),
(7, '3'),
(7, '6'),
(7, '8'),
(8, '1968'),
(8, '1969'),
(8, '1975'),
(9, 'Hammer'),
(9, 'Key'),
(9, 'Fork'),
(10, 'Carrillo'),
(10, 'Guerrero'),
(10, 'Cueva');
